### ISSUE TITLE
初回起動時、tmpディレクトリが存在せず実行に失敗する

### ISSUE THREAD

**Issue by hanasuke** [morivden/WSP_docker_online_judge#7]
以下エラーログです。

```
2017-09-22 19:49:53 - Errno::ENOENT - No such file or directory @ rb_sysopen - tmp/1506077393.265862.ruby:
	app.rb:24:in `initialize'
	app.rb:24:in `open'
	app.rb:24:in `block in <main>'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `block in compile!'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (3 levels) in route!'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1010:in `route_eval'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (2 levels) in route!'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1037:in `block in process_route'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `catch'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `process_route'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:989:in `block in route!'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `each'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `route!'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1094:in `block in dispatch!'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1091:in `dispatch!'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/logger.rb:15:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:231:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:224:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/show_exceptions.rb:22:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:194:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1955:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `block in call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1726:in `synchronize'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `call'
	/Users/naosuke/Develop/SLP/wsp/team-niku/.bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
	/Users/naosuke/.rbenv/versions/2.4.0/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
	/Users/naosuke/.rbenv/versions/2.4.0/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
	/Users/naosuke/.rbenv/versions/2.4.0/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
::1 - - [22/Sep/2017:19:49:53 JST] "POST /api/run HTTP/1.1" 500 138171
```

**Comment by morivden** [comment]
.gitignoreの設定が/tmp/* になっているのが原因かもしれないので修正しておきます。
